<?php $title = $this->getTitle() ?>
<?php $selector = 'slider'.md5(rand()); //rand(0,666666); ?>
<?php $categories = $this->getCategories(); if(!count($categories)) return;?>
<div id="<?php echo $selector ?>">
    <?php echo $title ? '<h2 class="title item">' . '<span>' .$title. '</span>' . '</h2>' : '' ?>
    <ul class="categories">
    <?php foreach ($categories as $cat) :?>
        <li class="cat-item">
            <a href="<?php echo $cat->getUrl() ? $cat->getUrl() : '#' ?>">
				<?php if($img = $cat->getMagicImage()): ?>
                <img class="cat img-responsive" src="<?php echo Mage::getBaseUrl ( 'media' ) ."/catalog/category/" . $img;?>" alt="<?php echo $this->__($cat->getName()) ?>" title="<?php echo $this->__($cat->getName()) ?>" />
				<?php endif ?>
			</a>
			<div class="categories-inner">
				<h3 class="cat-title"><a href="<?php echo $cat->getUrl() ? $cat->getUrl() : '#' ?>"><?php echo $cat->getName() ?></a></h3>
				<div class="short_desc"><?php echo $cat->getDescription() ?></div>
				<a class="view-categoris" href="<?php echo $cat->getUrl() ? $cat->getUrl() : '#' ?>"><?php echo $this->__('View More'); ?></a>
			</div>
        </li>
    <?php endforeach ?>
    </ul>
</div>

<script type="text/javascript">
    jQuery( document ).ready(function($) {
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.categories', $content);
            $slider.bxSlider({
                <?php //echo $this->getSlider() ?>
				auto: true,
                slideWidth: 220,
                slideMargin: 10,
                pager:false,
                minSlides: 5,
                maxSlides: 5,
                visibleItems:5,
                infiniteLoop: false,
                moveSlides: 1,
                responsiveBreakpoints : {480: 1, 640: 2, 768: 3, 900: 5},
            });

        })("#<?php echo $selector ?>");
    });
	</script>

